version: "3.3"
services:
  node_with_redis:
    container_name: node_with_redis
    working_dir: /app
    build:
      context: ./
      dockerfile: ./infra/development/Dockerfile
    volumes:
      - ./:/app
    env_file:
      - ./infra/development/.env
    ports:
      - "3000:3000"

    redis:
        container_name: redis_container
        image: redis:5-alpine

    redis_commander:
        container_name: redis_commander_container
        image: rediscommander/redis-commander:latest
        restart: always
        ports:
          - "3001:8081"