version: "3.3"
services:
 node_with_redis:
    container_name: node_with_redis
    privileged: true
    working_dir: /app
    build:
      context: ./
      dockerfile: ./infra/development/Dockerfile
    depends_on: 
        - redis_container
    links:
        - redis_container
    volumes:
      - ./:/app
    env_file:
      - ./infra/development/.env
    ports:
      - "3000:3000"

 redis_container:
    container_name: redis_container
    image: redis:6.0.6-alpine

 redis_commander_container:
    container_name: redis_commander_container
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
        - "3001:8081"